project:
  title: Barrier Book
  type: website
  render:
    - index.qmd
    - cloures.qmd
    - storm.qmd
  output-dir: docs
  lib-dir: site_libs


website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cloures.qmd
        text: Closures
      - href: storm.qmd
        text: Storm Analysis
